# Generated by Django 5.0.3 on 2024-03-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lettitude',
            new_name='letitude',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='longitudev',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Vendor'), (2, 'Customer')], null=True),
        ),
    ]
