# Generated by Django 5.0.3 on 2024-03-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_vendors'),
        ('vendor', '0004_openinghour'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Vendors',
            field=models.ManyToManyField(blank=True, to='vendor.vendor'),
        ),
    ]
